[project]
name = "pixelgram-backend"
version = "0.1.0"
description = "Pixelgram is a minimal social media for pixel art content."
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "psycopg2>=2.9.10",
    "pydantic-settings>=2.8.1",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]
