volumes:
    postgres-data:

networks:
    dev-network:

services:
    devcontainer:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_URI: postgresql://postgres:postgres@db:5432/postgres
        volumes:
            - ../..:/workspaces/${localWorkspaceFolderBasename}:cached

        command: sleep infinity # Keeps the container running
        networks:
            - dev-network
        depends_on:
            - db

    db:
        image: postgres:17-bookworm
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        networks:
            - dev-network
