name: Python CI

on:
    push:
        branches:
            - "**"
        paths:
            - "backend/**"
    pull_request:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install uv
              run: pip install uv
              working-directory: backend

            - name: Install dependencies with uv
              run: uv sync --frozen
              working-directory: backend

            - name: Check ruff formatting
              run: uv run ruff format --check
              working-directory: backend

            - name: Check ruff linting
              run: uv run ruff check
              working-directory: backend

            - name: Check tests pass
              run: uv run pytest
              working-directory: backend
